import Head from 'next/head';

import dynamic from 'next/dynamic';
const Navbar = dynamic(() => import('@/components/Navbar'), { ssr: false });
const Hero = dynamic(() => import('@/components/Hero'), { ssr: false });
const About = dynamic(() => import('@/components/About'), { ssr: false });
const Memories = dynamic(() => import('@/components/Memories'), { ssr: false });
const AnnualReport = dynamic(() => import('@/components/AnnualReport'), { ssr: false });
const Footer = dynamic(() => import('@/components/Footer'), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Leather for good</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <About />
        <Memories />
        <AnnualReport />
        <Footer />
      </main>
    </>
  );
}
